### ISSUE TITLE
Problem with data(package = "FactorAnalytics") 

### ISSUE THREAD

**Issue by martinrd3D** [braverock/FactorAnalytics#61]
Using current version of FA, the above responds with responds "no data sets found"

**Comment by martinrd3D** [comment]
This still does not work from my install, but it works when I have loaded FactorAnalytics as a project.  I guess maybe this is because of the LFS??

**Comment by JustinMShea** [comment]
@martinrd3D Its because we removed the load lazydata = true argument from the Description file
https://github.com/braverock/FactorAnalytics/commit/24121d17b8d0d9ea079702172e731c325118c27b

I did that due to this conversation: https://github.com/r-lib/remotes/issues/637. 

Ultimately, we will likely change it back if these problems persist.

**Comment by JustinMShea** [comment]
This is something we want to test and revisit, but it looks like we will not use the Lazydata feature due to this. @martinrd3D We can discuss the benefits as we start working on the data now
